-- PersonXAI — full schema (GENERATED by scripts/build-schema.mjs; do not edit).
-- Paste this whole file into Supabase → SQL Editor → New query → Run.
-- Equivalent to applying supabase/migrations/*.sql in order:
--   0001_core.sql
--   0002_conversations.sql
--   0003_agent_runs.sql
--   0004_projects_tasks_notes.sql
--   0005_inbox.sql
--   0006_reminders.sql
--   0007_scheduler_fns.sql
--   0008_files.sql
--   0009_memory_links.sql
--   0010_search_fns.sql
--   0011_skills.sql
--   0012_hardening.sql
--   0013_tags_vaults.sql
--   0014_wallet.sql

begin;

-- ══════════════════════════════════════════════════════════════════════
-- 0001_core.sql
-- ══════════════════════════════════════════════════════════════════════
-- 0001_core: extensions, shared trigger, users, user_identities, settings, audit_logs
-- Security model: Worker uses service_role only. RLS enabled with zero policies (deny-all
-- for anon/authenticated); per-user columns exist everywhere so real policies can be added later.

create extension if not exists vector with schema extensions;
create extension if not exists pg_trgm with schema extensions;

-- Shared updated_at trigger
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Enums
create type public.user_role as enum ('owner', 'admin', 'user', 'viewer');
create type public.msg_role as enum ('user', 'assistant', 'system', 'tool', 'system_routine_task');
create type public.actor_kind as enum ('user', 'agent', 'system');
create type public.entity_kind as enum (
  'project', 'task', 'note', 'file', 'reminder', 'link', 'memory',
  'inbox_item', 'skill', 'conversation', 'setting', 'user'
);

-- Users (channel-agnostic; identities live in user_identities)
create table public.users (
  id uuid primary key default gen_random_uuid(),
  role public.user_role not null default 'user',
  is_allowed boolean not null default false,
  display_name text,
  timezone text not null default 'UTC',
  language text not null default 'en',
  autonomy_level smallint not null default 1 check (autonomy_level between 0 and 3),
  tz_confirmed boolean not null default false,
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger users_set_updated_at before update on public.users
  for each row execute function public.set_updated_at();

-- One row per (channel, external id); a user can have identities on many channels
create table public.user_identities (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  channel text not null,
  external_id text not null,
  chat_ref text,
  username text,
  created_at timestamptz not null default now(),
  unique (channel, external_id)
);
create index user_identities_user_id_idx on public.user_identities (user_id);

create table public.settings (
  user_id uuid not null references public.users(id) on delete cascade,
  key text not null,
  value jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (user_id, key)
);
create trigger settings_set_updated_at before update on public.settings
  for each row execute function public.set_updated_at();

create table public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.users(id) on delete set null,
  actor public.actor_kind not null,
  action text not null,
  entity_kind public.entity_kind,
  entity_id uuid,
  details jsonb not null default '{}',
  status text not null default 'ok',
  created_at timestamptz not null default now()
);
create index audit_logs_user_created_idx on public.audit_logs (user_id, created_at desc);

-- Deny-all: RLS on, no policies; only service_role (bypasses RLS) can access
alter table public.users enable row level security;
alter table public.user_identities enable row level security;
alter table public.settings enable row level security;
alter table public.audit_logs enable row level security;

revoke all on all tables in schema public from anon, authenticated;
alter default privileges in schema public revoke all on tables from anon, authenticated;
alter default privileges in schema public revoke all on functions from anon, authenticated;
alter default privileges in schema public revoke all on sequences from anon, authenticated;

-- ══════════════════════════════════════════════════════════════════════
-- 0002_conversations.sql
-- ══════════════════════════════════════════════════════════════════════
-- 0002_conversations: conversation contexts + messages with embeddings

create table public.conversations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  project_id uuid, -- FK added in 0004 once projects exists
  title text,
  is_active boolean not null default false,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger conversations_set_updated_at before update on public.conversations
  for each row execute function public.set_updated_at();
create index conversations_user_id_idx on public.conversations (user_id, created_at desc);
-- exactly one active conversation (context) per user
create unique index conversations_one_active_per_user_idx
  on public.conversations (user_id) where is_active;

create table public.messages (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  role public.msg_role not null,
  content text not null,
  channel text,               -- e.g. 'telegram'; null for internal/system turns
  external_message_id text,   -- channel-native message id
  media jsonb,                -- normalized media refs when the turn carried attachments
  tokens_in integer,
  tokens_out integer,
  embedding extensions.vector(1024),
  created_at timestamptz not null default now()
);
create index messages_conversation_created_idx on public.messages (conversation_id, created_at);
create index messages_user_created_idx on public.messages (user_id, created_at desc);
create index messages_embedding_idx on public.messages
  using hnsw (embedding extensions.vector_cosine_ops)
  with (m = 16, ef_construction = 64)
  where embedding is not null;

alter table public.conversations enable row level security;
alter table public.messages enable row level security;

-- ══════════════════════════════════════════════════════════════════════
-- 0003_agent_runs.sql
-- ══════════════════════════════════════════════════════════════════════
-- 0003_agent_runs: per-turn accounting + tool call audit

create type public.run_status as enum ('ok', 'error', 'aborted');
create type public.run_trigger as enum (
  'message', 'command', 'callback', 'schedule', 'heartbeat', 'daily_brief', 'dispatch'
);

create table public.agent_runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  conversation_id uuid references public.conversations(id) on delete set null,
  trigger public.run_trigger not null,
  model text,
  iterations integer not null default 0,
  tool_call_count integer not null default 0,
  prompt_tokens integer,
  completion_tokens integer,
  cost_usd numeric(10, 6),
  status public.run_status not null,
  error text,
  latency_ms integer,
  created_at timestamptz not null default now()
);
create index agent_runs_user_created_idx on public.agent_runs (user_id, created_at desc);
create index agent_runs_conversation_idx on public.agent_runs (conversation_id);

create table public.tool_calls (
  id uuid primary key default gen_random_uuid(),
  run_id uuid not null references public.agent_runs(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  tool_name text not null,
  args jsonb,           -- redacted before insert
  result_summary text,  -- truncated
  status text not null,
  error text,
  duration_ms integer,
  created_at timestamptz not null default now()
);
create index tool_calls_run_id_idx on public.tool_calls (run_id);
create index tool_calls_user_created_idx on public.tool_calls (user_id, created_at desc);

alter table public.agent_runs enable row level security;
alter table public.tool_calls enable row level security;

-- ══════════════════════════════════════════════════════════════════════
-- 0004_projects_tasks_notes.sql
-- ══════════════════════════════════════════════════════════════════════
-- 0004_projects_tasks_notes: project management layer + notes

create type public.project_status as enum (
  'idea', 'planned', 'active', 'waiting', 'blocked', 'completed', 'archived'
);
create type public.priority_level as enum ('critical', 'high', 'medium', 'low');
create type public.task_status as enum (
  'inbox', 'todo', 'in_progress', 'waiting', 'blocked', 'done', 'cancelled'
);
create type public.note_source as enum ('manual', 'research', 'url', 'file', 'voice', 'agent');

create table public.projects (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  name text not null,
  slug text not null,
  description text,
  status public.project_status not null default 'active',
  priority public.priority_level not null default 'medium',
  category text,
  start_date date,
  due_date date,
  progress smallint not null default 0 check (progress between 0 and 100),
  tags text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, slug)
);
create trigger projects_set_updated_at before update on public.projects
  for each row execute function public.set_updated_at();
create index projects_user_status_idx on public.projects (user_id, status);
create index projects_tags_idx on public.projects using gin (tags);

create table public.project_members (
  project_id uuid not null references public.projects(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  role public.user_role not null default 'user',
  created_at timestamptz not null default now(),
  primary key (project_id, user_id)
);
create index project_members_user_id_idx on public.project_members (user_id);

create table public.tasks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  project_id uuid references public.projects(id) on delete set null,
  parent_task_id uuid references public.tasks(id) on delete cascade,
  title text not null,
  description text,
  status public.task_status not null default 'todo',
  priority public.priority_level not null default 'medium',
  start_at timestamptz,
  due_at timestamptz,
  recurrence_rule text,
  tags text[] not null default '{}',
  source text not null default 'chat',
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger tasks_set_updated_at before update on public.tasks
  for each row execute function public.set_updated_at();
create index tasks_user_status_due_idx on public.tasks (user_id, status, due_at);
create index tasks_project_id_idx on public.tasks (project_id);
create index tasks_parent_task_id_idx on public.tasks (parent_task_id);
create index tasks_tags_idx on public.tasks using gin (tags);

create table public.task_dependencies (
  task_id uuid not null references public.tasks(id) on delete cascade,
  depends_on_task_id uuid not null references public.tasks(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (task_id, depends_on_task_id),
  check (task_id <> depends_on_task_id)
);
create index task_dependencies_depends_on_idx on public.task_dependencies (depends_on_task_id);

create table public.notes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  project_id uuid references public.projects(id) on delete set null,
  title text,
  content text not null,
  source public.note_source not null default 'manual',
  tags text[] not null default '{}',
  pinned boolean not null default false,
  embedding extensions.vector(1024),
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger notes_set_updated_at before update on public.notes
  for each row execute function public.set_updated_at();
create index notes_user_created_idx on public.notes (user_id, created_at desc) where deleted_at is null;
create index notes_project_id_idx on public.notes (project_id);
create index notes_tags_idx on public.notes using gin (tags);
create index notes_fts_idx on public.notes
  using gin (to_tsvector('simple', coalesce(title, '') || ' ' || content));
create index notes_embedding_idx on public.notes
  using hnsw (embedding extensions.vector_cosine_ops)
  with (m = 16, ef_construction = 64)
  where deleted_at is null;

alter table public.conversations
  add constraint conversations_project_id_fkey
  foreign key (project_id) references public.projects(id) on delete set null;
create index conversations_project_id_idx on public.conversations (project_id);

alter table public.projects enable row level security;
alter table public.project_members enable row level security;
alter table public.tasks enable row level security;
alter table public.task_dependencies enable row level security;
alter table public.notes enable row level security;

-- ══════════════════════════════════════════════════════════════════════
-- 0005_inbox.sql
-- ══════════════════════════════════════════════════════════════════════
-- 0005_inbox: universal capture inbox with AI classification cache

create type public.inbox_source as enum ('message', 'file', 'link', 'forward', 'voice', 'photo');
create type public.inbox_status as enum ('pending', 'organized', 'dismissed');

create table public.inbox_items (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  source public.inbox_source not null,
  raw_content text,
  channel text,
  external_message_id text,
  media jsonb,
  suggested_kind public.entity_kind,
  suggested_project_id uuid references public.projects(id) on delete set null,
  classification jsonb,       -- cached small-model output {kind, project, tags, confidence}
  status public.inbox_status not null default 'pending',
  resolved_kind public.entity_kind,
  resolved_entity_id uuid,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger inbox_items_set_updated_at before update on public.inbox_items
  for each row execute function public.set_updated_at();
create index inbox_items_user_status_idx on public.inbox_items (user_id, status, created_at desc);
create index inbox_items_suggested_project_idx on public.inbox_items (suggested_project_id);

alter table public.inbox_items enable row level security;

-- ══════════════════════════════════════════════════════════════════════
-- 0006_reminders.sql
-- ══════════════════════════════════════════════════════════════════════
-- 0006_reminders: reminders + transactional job outbox
-- Ported from openmemo (github.com/haerincode/openmemo) migrations 0001_init_office.sql,
-- generalized to multi-user and trimmed to the kinds this project uses.

create type public.reminder_kind as enum ('static', 'recurring', 'dynamic');
create type public.reminder_status as enum (
  'scheduled', 'active', 'paused', 'completed', 'cancelled', 'failed'
);
create type public.job_status as enum ('pending', 'in_flight', 'delivered', 'failed', 'dead_letter');

create table public.reminders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  kind public.reminder_kind not null default 'static',
  status public.reminder_status not null default 'scheduled',
  content text,                  -- what to remind about (directive for the agent, not verbatim user text)
  raw_text text,                 -- original user phrasing
  recurrence_rule text,          -- RRULE string for recurring
  start_at timestamptz,
  next_trigger_at timestamptz,
  deadline_at timestamptz,
  timezone text not null default 'UTC',
  template_id text,              -- 'daily_brief' | 'heartbeat' for dynamic kind
  template_params jsonb,
  linked_task_id uuid references public.tasks(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (kind <> 'recurring' or recurrence_rule is not null),
  check (kind <> 'dynamic' or template_id is not null)
);
create trigger reminders_set_updated_at before update on public.reminders
  for each row execute function public.set_updated_at();
create index reminders_due_idx on public.reminders (next_trigger_at)
  where status in ('scheduled', 'active');
create index reminders_user_status_idx on public.reminders (user_id, status);
create index reminders_linked_task_idx on public.reminders (linked_task_id);

create table public.job_outbox (
  id uuid primary key default gen_random_uuid(),
  reminder_id uuid not null references public.reminders(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  occurrence_at timestamptz not null,
  idempotency_key text not null unique,  -- 'rem:<reminder_id>:<epoch>'
  status public.job_status not null default 'pending',
  attempts integer not null default 0,
  next_attempt_at timestamptz not null default now(),
  last_error text,
  in_flight_until timestamptz,
  delivered_at timestamptz,
  created_at timestamptz not null default now()
);
create index job_outbox_due_idx on public.job_outbox (next_attempt_at)
  where status in ('pending', 'in_flight');
create index job_outbox_reminder_id_idx on public.job_outbox (reminder_id);
create index job_outbox_user_id_idx on public.job_outbox (user_id);

alter table public.reminders enable row level security;
alter table public.job_outbox enable row level security;

-- ══════════════════════════════════════════════════════════════════════
-- 0007_scheduler_fns.sql
-- ══════════════════════════════════════════════════════════════════════
-- 0007_scheduler_fns: outbox scheduler functions
-- Ported from openmemo (github.com/haerincode/openmemo) 0004_scheduler_fns.sql.
-- Called by the Worker dispatcher via supabase-js .rpc() on every cron tick (no pg_cron).
-- All SECURITY DEFINER, service_role-only.

-- Materialize due reminders into the outbox (idempotent via idempotency_key)
create or replace function public.select_due_reminders()
returns integer
language sql
security definer
set search_path = ''
as $$
  with inserted as (
    insert into public.job_outbox (reminder_id, user_id, occurrence_at, idempotency_key)
    select
      r.id,
      r.user_id,
      r.next_trigger_at,
      'rem:' || r.id::text || ':' || extract(epoch from r.next_trigger_at)::bigint
    from public.reminders r
    where r.status in ('scheduled', 'active')
      and r.next_trigger_at is not null
      and r.next_trigger_at <= now()
    on conflict (idempotency_key) do nothing
    returning 1
  )
  select coalesce(count(*), 0)::integer from inserted;
$$;

-- Claim a batch of due jobs with queue semantics:
-- FOR UPDATE SKIP LOCKED + 2-minute visibility lease; stale in_flight jobs are reclaimed.
create or replace function public.claim_due_jobs(p_batch integer default 20)
returns table (
  job_id uuid,
  reminder_id uuid,
  user_id uuid,
  occurrence_at timestamptz,
  attempts integer,
  kind public.reminder_kind,
  content text,
  raw_text text,
  recurrence_rule text,
  timezone text,
  template_id text,
  template_params jsonb,
  linked_task_id uuid
)
language sql
security definer
set search_path = ''
as $$
  with claimed as (
    update public.job_outbox j
    set status = 'in_flight',
        attempts = j.attempts + 1,
        in_flight_until = now() + interval '2 minutes'
    where j.id in (
      select id from public.job_outbox
      where (status = 'pending' and next_attempt_at <= now())
         or (status = 'in_flight' and in_flight_until < now())
      order by next_attempt_at asc
      limit p_batch
      for update skip locked
    )
    returning j.id, j.reminder_id, j.user_id, j.occurrence_at, j.attempts
  )
  select
    c.id as job_id,
    c.reminder_id,
    c.user_id,
    c.occurrence_at,
    c.attempts,
    r.kind,
    r.content,
    r.raw_text,
    r.recurrence_rule,
    r.timezone,
    r.template_id,
    r.template_params,
    r.linked_task_id
  from claimed c
  join public.reminders r on r.id = c.reminder_id;
$$;

create or replace function public.mark_job_delivered(p_job_id uuid)
returns void
language sql
security definer
set search_path = ''
as $$
  update public.job_outbox
  set status = 'delivered', delivered_at = now(), in_flight_until = null
  where id = p_job_id;
$$;

-- Exponential backoff (2^attempts minutes), dead-letter after 5 attempts
create or replace function public.mark_job_failed(p_job_id uuid, p_error text)
returns public.job_status
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_job public.job_outbox%rowtype;
  v_status public.job_status;
begin
  select * into v_job from public.job_outbox where id = p_job_id for update;
  if not found then
    return null;
  end if;

  if v_job.attempts >= 5 then
    v_status := 'dead_letter';
    update public.job_outbox
    set status = 'dead_letter', last_error = p_error, in_flight_until = null
    where id = p_job_id;
  else
    v_status := 'pending';
    update public.job_outbox
    set status = 'pending',
        last_error = p_error,
        in_flight_until = null,
        next_attempt_at = now() + (power(2, v_job.attempts)::text || ' minutes')::interval
    where id = p_job_id;
  end if;

  return v_status;
end;
$$;

revoke execute on function public.select_due_reminders() from public, anon, authenticated;
revoke execute on function public.claim_due_jobs(integer) from public, anon, authenticated;
revoke execute on function public.mark_job_delivered(uuid) from public, anon, authenticated;
revoke execute on function public.mark_job_failed(uuid, text) from public, anon, authenticated;
grant execute on function public.select_due_reminders() to service_role;
grant execute on function public.claim_due_jobs(integer) to service_role;
grant execute on function public.mark_job_delivered(uuid) to service_role;
grant execute on function public.mark_job_failed(uuid, text) to service_role;

-- ══════════════════════════════════════════════════════════════════════
-- 0008_files.sql
-- ══════════════════════════════════════════════════════════════════════
-- 0008_files: file vault metadata, extraction chunks, tags
-- Vault pattern from TeleFileBot-CloudFlare: bytes live in a private Telegram
-- channel; Postgres holds metadata + extracted text only.

create type public.file_source as enum ('telegram', 'generated');
create type public.file_storage as enum ('vault', 'r2');
create type public.extraction_status as enum ('pending', 'done', 'failed', 'skipped');

create table public.files (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  project_id uuid references public.projects(id) on delete set null,
  file_name text not null,
  caption text,
  mime_type text,
  file_size bigint,
  media_kind text,                    -- document/photo/video/audio/voice/... (MediaKind)
  tg_file_id text,
  tg_file_unique_id text,
  vault_chat_id text,
  vault_message_id bigint,
  origin_chat_id text,                -- original chat + message for reply-linking
  origin_message_id text,
  storage public.file_storage not null default 'vault',
  r2_key text,
  source public.file_source not null default 'telegram',
  extraction_status public.extraction_status not null default 'pending',
  extracted_text text,
  summary text,
  embedding extensions.vector(1024), -- of summary/caption
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, tg_file_unique_id)
);
create trigger files_set_updated_at before update on public.files
  for each row execute function public.set_updated_at();
create index files_user_created_idx on public.files (user_id, created_at desc) where deleted_at is null;
create index files_project_id_idx on public.files (project_id);
create index files_name_trgm_idx on public.files using gin (file_name extensions.gin_trgm_ops);
create index files_fts_idx on public.files
  using gin (to_tsvector('simple', coalesce(file_name, '') || ' ' || coalesce(caption, '') || ' ' || coalesce(extracted_text, '')));
create index files_origin_idx on public.files (user_id, origin_message_id);
create index files_embedding_idx on public.files
  using hnsw (embedding extensions.vector_cosine_ops)
  with (m = 16, ef_construction = 64)
  where deleted_at is null;

create table public.file_chunks (
  id uuid primary key default gen_random_uuid(),
  file_id uuid not null references public.files(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  chunk_index integer not null,
  content text not null,
  embedding extensions.vector(1024),
  created_at timestamptz not null default now(),
  unique (file_id, chunk_index)
);
create index file_chunks_user_id_idx on public.file_chunks (user_id);
create index file_chunks_embedding_idx on public.file_chunks
  using hnsw (embedding extensions.vector_cosine_ops)
  with (m = 16, ef_construction = 64);

create table public.tags (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  unique (user_id, name)
);

create table public.file_tags (
  file_id uuid not null references public.files(id) on delete cascade,
  tag_id uuid not null references public.tags(id) on delete cascade,
  primary key (file_id, tag_id)
);
create index file_tags_tag_id_idx on public.file_tags (tag_id);

alter table public.files enable row level security;
alter table public.file_chunks enable row level security;
alter table public.tags enable row level security;
alter table public.file_tags enable row level security;

-- ══════════════════════════════════════════════════════════════════════
-- 0009_memory_links.sql
-- ══════════════════════════════════════════════════════════════════════
-- 0009_memory_links: long-term memory (typed + vector), user facts (KV), bookmarks
-- Memory split follows openmemo: KV facts are injected into every prompt, while
-- vector memories are retrieved on demand.

create type public.memory_type as enum (
  'preference', 'decision', 'project_context', 'fact', 'workflow', 'event'
);

create table public.memories (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  project_id uuid references public.projects(id) on delete set null,
  memory_type public.memory_type not null default 'fact',
  content text not null,
  tags text[] not null default '{}',
  importance smallint not null default 3 check (importance between 1 and 5),
  embedding extensions.vector(1024),
  source_message_id uuid references public.messages(id) on delete set null,
  last_accessed_at timestamptz,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger memories_set_updated_at before update on public.memories
  for each row execute function public.set_updated_at();
create index memories_user_created_idx on public.memories (user_id, created_at desc)
  where deleted_at is null;
create index memories_project_id_idx on public.memories (project_id);
create index memories_source_message_idx on public.memories (source_message_id);
create index memories_tags_idx on public.memories using gin (tags);
create index memories_embedding_idx on public.memories
  using hnsw (embedding extensions.vector_cosine_ops)
  with (m = 16, ef_construction = 64)
  where deleted_at is null;

-- Structured facts about the user, injected into every system prompt.
-- The key IS the dedup: upsert on (user_id, key).
create table public.user_facts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  category text not null default 'general',
  key text not null,
  value text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, key)
);
create trigger user_facts_set_updated_at before update on public.user_facts
  for each row execute function public.set_updated_at();

create table public.links (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  project_id uuid references public.projects(id) on delete set null,
  url text not null,
  title text,
  description text,
  site_name text,
  summary text,
  tags text[] not null default '{}',
  embedding extensions.vector(1024),
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, url)
);
create trigger links_set_updated_at before update on public.links
  for each row execute function public.set_updated_at();
create index links_user_created_idx on public.links (user_id, created_at desc)
  where deleted_at is null;
create index links_project_id_idx on public.links (project_id);
create index links_tags_idx on public.links using gin (tags);
create index links_embedding_idx on public.links
  using hnsw (embedding extensions.vector_cosine_ops)
  with (m = 16, ef_construction = 64)
  where deleted_at is null;

alter table public.memories enable row level security;
alter table public.user_facts enable row level security;
alter table public.links enable row level security;

-- ══════════════════════════════════════════════════════════════════════
-- 0010_search_fns.sql
-- ══════════════════════════════════════════════════════════════════════
-- 0010_search_fns: vector + hybrid retrieval RPCs.
-- All are user-scoped, SECURITY DEFINER, service_role-only. Vector ordering is
-- impossible through PostgREST's query builder, so every similarity search goes
-- through one of these functions.
-- Callers apply their own similarity thresholds (openmemo pattern): memories ~0.3,
-- conversation recall ~0.7.
-- Keyword matching uses strpos() containment so user text needs no LIKE-escaping.

create or replace function public.match_memories(
  p_user_id uuid,
  p_query_embedding extensions.vector(1024),
  p_project uuid default null,
  p_tag_filter text[] default null,
  p_limit int default 10
)
returns table (id uuid, content text, memory_type public.memory_type, tags text[],
               importance smallint, project_id uuid, similarity float)
language sql
stable
security definer
set search_path = ''
as $fn$
  select m.id, m.content, m.memory_type, m.tags, m.importance, m.project_id,
         (1 - (m.embedding operator(extensions.<=>) p_query_embedding))::float as similarity
  from public.memories m
  where m.user_id = p_user_id
    and m.deleted_at is null
    and m.embedding is not null
    and (p_project is null or m.project_id = p_project)
    and (p_tag_filter is null or m.tags && p_tag_filter)
  order by m.embedding operator(extensions.<=>) p_query_embedding
  limit p_limit;
$fn$;

create or replace function public.match_file_chunks(
  p_user_id uuid,
  p_query_embedding extensions.vector(1024),
  p_project uuid default null,
  p_limit int default 8
)
returns table (chunk_id uuid, file_id uuid, file_name text, chunk_index int,
               content text, similarity float)
language sql
stable
security definer
set search_path = ''
as $fn$
  select c.id, c.file_id, f.file_name, c.chunk_index, c.content,
         (1 - (c.embedding operator(extensions.<=>) p_query_embedding))::float as similarity
  from public.file_chunks c
  join public.files f on f.id = c.file_id
  where c.user_id = p_user_id
    and c.embedding is not null
    and f.deleted_at is null
    and (p_project is null or f.project_id = p_project)
  order by c.embedding operator(extensions.<=>) p_query_embedding
  limit p_limit;
$fn$;

create or replace function public.match_messages(
  p_user_id uuid,
  p_conversation uuid,
  p_query_embedding extensions.vector(1024),
  p_limit int default 5
)
returns table (id uuid, role public.msg_role, content text, created_at timestamptz,
               similarity float)
language sql
stable
security definer
set search_path = ''
as $fn$
  select m.id, m.role, m.content, m.created_at,
         (1 - (m.embedding operator(extensions.<=>) p_query_embedding))::float as similarity
  from public.messages m
  where m.user_id = p_user_id
    and m.embedding is not null
    and (p_conversation is null or m.conversation_id = p_conversation)
  order by m.embedding operator(extensions.<=>) p_query_embedding
  limit p_limit;
$fn$;

create or replace function public.match_notes(
  p_user_id uuid,
  p_query_embedding extensions.vector(1024),
  p_project uuid default null,
  p_limit int default 8
)
returns table (id uuid, title text, content text, tags text[], similarity float)
language sql
stable
security definer
set search_path = ''
as $fn$
  select n.id, n.title, n.content, n.tags,
         (1 - (n.embedding operator(extensions.<=>) p_query_embedding))::float as similarity
  from public.notes n
  where n.user_id = p_user_id
    and n.deleted_at is null
    and n.embedding is not null
    and (p_project is null or n.project_id = p_project)
  order by n.embedding operator(extensions.<=>) p_query_embedding
  limit p_limit;
$fn$;

-- Hybrid search: reciprocal-rank fusion (1/(60+rank)) of keyword and vector hits
-- across entity kinds. p_query_embedding may be null, in which case this
-- degrades gracefully to pure keyword search.
create or replace function public.hybrid_search(
  p_user_id uuid,
  p_query text,
  p_query_embedding extensions.vector(1024) default null,
  p_kinds public.entity_kind[] default null,
  p_limit int default 20
)
returns table (kind public.entity_kind, id uuid, title text, snippet text, score float)
language sql
stable
security definer
set search_path = ''
as $fn$
  with q as (select lower(p_query) as needle),
  keyword as (
    select 'project'::public.entity_kind as kind, p.id, p.name as title,
           left(coalesce(p.description, p.name), 200) as snippet,
           row_number() over (order by p.updated_at desc) as rnk
    from public.projects p, q
    where p.user_id = p_user_id
      and (strpos(lower(p.name), q.needle) > 0
           or strpos(lower(coalesce(p.description, '')), q.needle) > 0)
    union all
    select 'task', t.id, t.title, left(coalesce(t.description, t.title), 200),
           row_number() over (order by t.updated_at desc)
    from public.tasks t, q
    where t.user_id = p_user_id
      and (strpos(lower(t.title), q.needle) > 0
           or strpos(lower(coalesce(t.description, '')), q.needle) > 0)
    union all
    select 'note', n.id, coalesce(n.title, left(n.content, 60)), left(n.content, 200),
           row_number() over (order by n.updated_at desc)
    from public.notes n, q
    where n.user_id = p_user_id and n.deleted_at is null
      and (strpos(lower(n.content), q.needle) > 0
           or strpos(lower(coalesce(n.title, '')), q.needle) > 0)
    union all
    select 'file', f.id, f.file_name,
           left(coalesce(f.caption, f.extracted_text, f.file_name), 200),
           row_number() over (order by f.created_at desc)
    from public.files f, q
    where f.user_id = p_user_id and f.deleted_at is null
      and (strpos(lower(f.file_name), q.needle) > 0
           or strpos(lower(coalesce(f.caption, '')), q.needle) > 0
           or strpos(lower(coalesce(f.extracted_text, '')), q.needle) > 0)
    union all
    select 'link', l.id, coalesce(l.title, l.url),
           left(coalesce(l.summary, l.description, l.url), 200),
           row_number() over (order by l.created_at desc)
    from public.links l, q
    where l.user_id = p_user_id and l.deleted_at is null
      and (strpos(lower(l.url), q.needle) > 0
           or strpos(lower(coalesce(l.title, '')), q.needle) > 0
           or strpos(lower(coalesce(l.summary, '')), q.needle) > 0)
    union all
    select 'memory', m.id, left(m.content, 60), left(m.content, 200),
           row_number() over (order by m.importance desc, m.created_at desc)
    from public.memories m, q
    where m.user_id = p_user_id and m.deleted_at is null
      and strpos(lower(m.content), q.needle) > 0
  ),
  vector_hits as (
    select 'memory'::public.entity_kind as kind, v.id, left(v.content, 60) as title,
           left(v.content, 200) as snippet,
           row_number() over (order by v.similarity desc) as rnk
    from public.match_memories(p_user_id, p_query_embedding, null, null, 10) v
    where p_query_embedding is not null
    union all
    select 'note', n.id, coalesce(n.title, left(n.content, 60)), left(n.content, 200),
           row_number() over (order by n.similarity desc)
    from public.match_notes(p_user_id, p_query_embedding, null, 10) n
    where p_query_embedding is not null
    union all
    select 'file', c.file_id, c.file_name, left(c.content, 200),
           row_number() over (order by c.similarity desc)
    from public.match_file_chunks(p_user_id, p_query_embedding, null, 10) c
    where p_query_embedding is not null
  ),
  fused as (
    select all_hits.kind, all_hits.id, min(all_hits.title) as title,
           min(all_hits.snippet) as snippet,
           sum(1.0 / (60 + all_hits.rnk)) as score
    from (select * from keyword union all select * from vector_hits) all_hits
    group by all_hits.kind, all_hits.id
  )
  select f.kind, f.id, f.title, f.snippet, f.score::float
  from fused f
  where p_kinds is null or f.kind = any(p_kinds)
  order by f.score desc
  limit p_limit;
$fn$;

revoke execute on function public.match_memories(uuid, extensions.vector, uuid, text[], int) from public, anon, authenticated;
revoke execute on function public.match_file_chunks(uuid, extensions.vector, uuid, int) from public, anon, authenticated;
revoke execute on function public.match_messages(uuid, uuid, extensions.vector, int) from public, anon, authenticated;
revoke execute on function public.match_notes(uuid, extensions.vector, uuid, int) from public, anon, authenticated;
revoke execute on function public.hybrid_search(uuid, text, extensions.vector, public.entity_kind[], int) from public, anon, authenticated;
grant execute on function public.match_memories(uuid, extensions.vector, uuid, text[], int) to service_role;
grant execute on function public.match_file_chunks(uuid, extensions.vector, uuid, int) to service_role;
grant execute on function public.match_messages(uuid, uuid, extensions.vector, int) to service_role;
grant execute on function public.match_notes(uuid, extensions.vector, uuid, int) to service_role;
grant execute on function public.hybrid_search(uuid, text, extensions.vector, public.entity_kind[], int) to service_role;

-- ══════════════════════════════════════════════════════════════════════
-- 0011_skills.sql
-- ══════════════════════════════════════════════════════════════════════
-- 0011_skills: skill registry, MCP server registry, versioned personalization layer

create table public.skills (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.users(id) on delete cascade,  -- null = built-in / global
  name text not null,
  description text,
  instructions text not null,
  tools text[] not null default '{}',      -- tool names this skill may use ('*' = all registered)
  permission_level text not null default 'write',
  triggers jsonb not null default '{}',    -- { keywords: [], commands: [] }
  input_schema jsonb,
  version integer not null default 1,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger skills_set_updated_at before update on public.skills
  for each row execute function public.set_updated_at();
-- Per-user names are unique; global skills (user_id null) are unique on their own.
create unique index skills_user_name_idx on public.skills (user_id, name) where user_id is not null;
create unique index skills_global_name_idx on public.skills (name) where user_id is null;
create index skills_enabled_idx on public.skills (user_id, enabled);

create table public.mcp_servers (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  name text not null,
  url text not null,
  auth_header text,                        -- stored server-side only, never shown to the model
  enabled boolean not null default true,
  last_connected_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, name)
);
create trigger mcp_servers_set_updated_at before update on public.mcp_servers
  for each row execute function public.set_updated_at();

-- Versioned personalization layer (natural-db pattern): the base prompt is
-- immutable in code; only this layer is editable, and only one row is active.
create table public.system_prompts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  prompt_content text not null,
  version integer not null default 1,
  created_by_role public.msg_role not null default 'user',
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);
create unique index system_prompts_one_active_idx on public.system_prompts (user_id)
  where is_active;
create index system_prompts_user_version_idx on public.system_prompts (user_id, version desc);

alter table public.skills enable row level security;
alter table public.mcp_servers enable row level security;
alter table public.system_prompts enable row level security;

-- ══════════════════════════════════════════════════════════════════════
-- 0012_hardening.sql
-- ══════════════════════════════════════════════════════════════════════
-- 0012_hardening: statement timeouts on user-facing search functions.
-- A pathological query must never pin the free-tier instance; the Worker's own
-- tool timeouts are the second line of defence.

alter function public.hybrid_search(uuid, text, extensions.vector, public.entity_kind[], int)
  set statement_timeout = '10s';
alter function public.match_memories(uuid, extensions.vector, uuid, text[], int)
  set statement_timeout = '5s';
alter function public.match_file_chunks(uuid, extensions.vector, uuid, int)
  set statement_timeout = '5s';
alter function public.match_messages(uuid, uuid, extensions.vector, int)
  set statement_timeout = '5s';
alter function public.match_notes(uuid, extensions.vector, uuid, int)
  set statement_timeout = '5s';

-- The dispatcher path must stay snappy: a slow claim blocks the whole tick.
alter function public.claim_due_jobs(int) set statement_timeout = '10s';
alter function public.select_due_reminders() set statement_timeout = '10s';

-- Re-assert the deny-all posture for anything added since 0001.
revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
revoke all on all functions in schema public from anon, authenticated;

-- ══════════════════════════════════════════════════════════════════════
-- 0013_tags_vaults.sql
-- ══════════════════════════════════════════════════════════════════════
-- 0013_tags_vaults: first-class tags on files + multiple vault channels + tag facets
--
-- Tags: every entity already carries `tags text[]` with a GIN index, except files,
-- which used a join table. Denormalise files onto the same shape so one query
-- form (`tags @> '{x}'`) serves every kind and grouping stays cheap. The join
-- tables remain (kept in sync by the repo) for anything that still reads them.
alter table public.files add column if not exists tags text[] not null default '{}';
update public.files f
   set tags = coalesce(
     (select array_agg(t.name order by t.name)
        from public.file_tags ft join public.tags t on t.id = ft.tag_id
       where ft.file_id = f.id), '{}')
 where f.tags = '{}';
create index if not exists files_tags_idx on public.files using gin (tags);

-- Vault channels: a user may connect several private Telegram channels, each with
-- a category and tags (parsed from the channel description), so files can be
-- routed to the right one. The env VAULT_CHANNEL_ID is registered lazily as the
-- default the first time a user's list is read.
create table public.vault_channels (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  chat_id text not null,                      -- telegram chat id, "-100…"
  title text,
  category text,                              -- one short label: research, personal, receipts …
  description text,                           -- raw channel description (source of category/tags)
  tags text[] not null default '{}',
  is_default boolean not null default false,
  enabled boolean not null default true,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, chat_id)
);
create trigger vault_channels_set_updated_at before update on public.vault_channels
  for each row execute function public.set_updated_at();
create unique index vault_channels_default_idx on public.vault_channels (user_id) where is_default;
create index vault_channels_tags_idx on public.vault_channels using gin (tags);
alter table public.vault_channels enable row level security;

-- Tag facets: one call returns every tag with per-kind counts, for /tags, the
-- dashboard chips, and the live-context "tags in use" line.
create or replace function public.tag_counts(p_user_id uuid)
returns table (name text, kind public.entity_kind, count bigint)
language sql
stable
set search_path = ''
as $fn$
  select x.name, x.kind, count(*)::bigint as count
  from (
    select unnest(t.tags) as name, 'task'::public.entity_kind as kind
      from public.tasks t where t.user_id = p_user_id and t.status not in ('done', 'cancelled')
    union all
    select unnest(p.tags), 'project'::public.entity_kind
      from public.projects p where p.user_id = p_user_id and p.status <> 'archived'
    union all
    select unnest(n.tags), 'note'::public.entity_kind
      from public.notes n where n.user_id = p_user_id and n.deleted_at is null
    union all
    select unnest(f.tags), 'file'::public.entity_kind
      from public.files f where f.user_id = p_user_id and f.deleted_at is null
    union all
    select unnest(l.tags), 'link'::public.entity_kind
      from public.links l where l.user_id = p_user_id and l.deleted_at is null
    union all
    select unnest(m.tags), 'memory'::public.entity_kind
      from public.memories m where m.user_id = p_user_id and m.deleted_at is null
  ) x
  group by x.name, x.kind
  order by count desc, x.name;
$fn$;

-- ══════════════════════════════════════════════════════════════════════
-- 0014_wallet.sql
-- ══════════════════════════════════════════════════════════════════════
-- 0014_wallet: personal money ledger — every expense and every bit of income,
-- with the running history the user can list, correct, and total.
--
-- One flat table rather than accounts + double entry: this tracks a person's
-- cash flow ("2 kg sugar, 25 LE"), not a business's books. Direction ('in' /
-- 'out') plus a per-entry currency is enough to answer "what did I spend this
-- month" and "what am I left with", and it keeps every write a single insert.
--
-- Deletes are soft, like notes and files: a mistyped amount stays recoverable
-- and the audit trail keeps meaning.

create type public.wallet_direction as enum ('in', 'out');

create table public.wallet_entries (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  direction public.wallet_direction not null,
  amount numeric(14, 2) not null check (amount > 0),
  currency text not null default 'EGP' check (char_length(currency) between 2 and 8),
  description text not null,
  category text,
  -- What was bought, when the user said it: "2 kg sugar" → quantity 2, unit 'kg'.
  quantity numeric(12, 3) check (quantity is null or quantity > 0),
  unit text,
  -- cash / card / bank / instapay … free text: the set differs per country.
  method text,
  occurred_at timestamptz not null default now(),
  project_id uuid references public.projects(id) on delete set null,
  tags text[] not null default '{}',
  note text,
  source text not null default 'chat',
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger wallet_entries_set_updated_at before update on public.wallet_entries
  for each row execute function public.set_updated_at();
create index wallet_entries_user_time_idx on public.wallet_entries (user_id, occurred_at desc)
  where deleted_at is null;
create index wallet_entries_user_category_idx on public.wallet_entries (user_id, category)
  where deleted_at is null;
create index wallet_entries_project_id_idx on public.wallet_entries (project_id);
create index wallet_entries_tags_idx on public.wallet_entries using gin (tags);
create index wallet_entries_fts_idx on public.wallet_entries
  using gin (to_tsvector('simple', description || ' ' || coalesce(category, '') || ' ' || coalesce(note, '')));

alter table public.wallet_entries enable row level security;

-- Totals per currency for a window. The window is half-open [from, to) so
-- month-to-month sums never double-count the boundary instant.
create or replace function public.wallet_summary(
  p_user_id uuid,
  p_from timestamptz default null,
  p_to timestamptz default null
)
returns table (currency text, money_in numeric, money_out numeric, net numeric, entries bigint)
language sql
stable
set search_path = ''
as $fn$
  select
    w.currency,
    coalesce(sum(w.amount) filter (where w.direction = 'in'), 0)::numeric,
    coalesce(sum(w.amount) filter (where w.direction = 'out'), 0)::numeric,
    (coalesce(sum(w.amount) filter (where w.direction = 'in'), 0)
      - coalesce(sum(w.amount) filter (where w.direction = 'out'), 0))::numeric,
    count(*)::bigint
  from public.wallet_entries w
  where w.user_id = p_user_id
    and w.deleted_at is null
    and (p_from is null or w.occurred_at >= p_from)
    and (p_to is null or w.occurred_at < p_to)
  group by w.currency
  order by 3 desc;
$fn$;

-- "Where does the money go" — one row per category/currency/direction.
create or replace function public.wallet_category_totals(
  p_user_id uuid,
  p_direction public.wallet_direction default null,
  p_from timestamptz default null,
  p_to timestamptz default null,
  p_limit int default 20
)
returns table (
  category text,
  currency text,
  direction public.wallet_direction,
  total numeric,
  entries bigint
)
language sql
stable
set search_path = ''
as $fn$
  select
    coalesce(w.category, '')::text,
    w.currency,
    w.direction,
    sum(w.amount)::numeric,
    count(*)::bigint
  from public.wallet_entries w
  where w.user_id = p_user_id
    and w.deleted_at is null
    and (p_direction is null or w.direction = p_direction)
    and (p_from is null or w.occurred_at >= p_from)
    and (p_to is null or w.occurred_at < p_to)
  group by 1, w.currency, w.direction
  order by 4 desc
  limit least(coalesce(p_limit, 20), 100);
$fn$;

-- Same posture as every other user-facing aggregate (0012): a pathological
-- window must not pin the instance.
alter function public.wallet_summary(uuid, timestamptz, timestamptz)
  set statement_timeout = '5s';
alter function public.wallet_category_totals(uuid, public.wallet_direction, timestamptz, timestamptz, int)
  set statement_timeout = '5s';

revoke all on public.wallet_entries from anon, authenticated;

commit;
