#!/usr/bin/env node
/**
 * Concatenates supabase/migrations/*.sql (in filename order) into a single
 * supabase/schema.sql that can be pasted into the Supabase SQL editor in one go.
 *
 *   npm run schema
 *
 * The migrations stay the source of truth; schema.sql is a generated
 * convenience for one-click setup and is checked in so the docs can link it.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dir = join(root, "supabase", "migrations");
const files = readdirSync(dir).filter((f) => f.endsWith(".sql")).sort();

const parts = [
  "-- PersonXAI — full schema (GENERATED by scripts/build-schema.mjs; do not edit).",
  "-- Paste this whole file into Supabase → SQL Editor → New query → Run.",
  "-- Equivalent to applying supabase/migrations/*.sql in order:",
  ...files.map((f) => `--   ${f}`),
  "",
  "begin;",
  "",
];
for (const f of files) {
  parts.push(`-- ══════════════════════════════════════════════════════════════════════`);
  parts.push(`-- ${f}`);
  parts.push(`-- ══════════════════════════════════════════════════════════════════════`);
  parts.push(readFileSync(join(dir, f), "utf8").trim());
  parts.push("");
}
parts.push("commit;", "");
writeFileSync(join(root, "supabase", "schema.sql"), parts.join("\n"));
console.log(`wrote supabase/schema.sql from ${files.length} migrations`);
